doctrine:
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      project_mapping:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Domain/Project/Adapters/Gateway/Doctrine'
        prefix: 'App\Domain\Project\Adapters\Gateway\Doctrine'
        alias: App\Domain\Project\Adapters\Gateway\Doctrine
